### ISSUE TITLE
Missing precipitation data?

### ISSUE THREAD

**Issue by luizribeiro** [lilopkins/metar-rs#12]
From this METAR:

```
KEWR 021451Z 23014G24KT 10SM -RA FEW012 SCT025 BKN040 BKN130 11/05 A2939 RMK AO2 RAE11B48 SLP952 P0003 60003 T01110050 55003
```

Perhaps we need to add this to the grammar?

**Comment by lilopkins** [comment]
Hi @luizribeiro , apologies for the delay.

If you are referring to the data after the `RMK` tag, this is currently out of scope for this project as this is not standardised outside of the US. Apologies for this.
