### ISSUE TITLE
A METAR with a missing 'Q' from the pressure field causes a panic rather than an error

### ISSUE THREAD

**Issue by ed-davies** [lilopkins/metar-rs#3]
Taking the sample test program and deleting the 'Q' at the start of the pressure field (the last field of the METAR text, was 'Q1006' but changed to just '1006') 

fn main() {
    let metar = "EGHI 282120Z 19015KT 140V220 6000 RA SCT006 BKN009 16/14 1006";
    let r = metar::Metar::parse(metar).unwrap();
    println!("{:#?}", r);
}

results in a panic message:

thread 'main' panicked at 'index out of bounds: the len is 4 but the index is 4', /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/slice/mod.rs:2717:10

For a simple syntax error like this I'd expect an error to be bubbled up, also resulting in a panic but from the unwrap() which is what I see if I introduce another syntax error earlier in the METAR text.

The problem was first observed in a more complex program which was re-parsing METARs originally downloaded from https://www.checkwx.com/. A lot of METARs from there were OK but this one seemed to have had this syntax error introduced further upstream as the checkwx parsing also failed to extract the pressure. The checkwx data was downloaded 2018-06-18T18:33:04Z and was (with whitespace flattened):

{ "results": 1, "data": [ { "icao": "EGPC", "name": "Wick", "observed": "18-06-2018 @ 17:50Z", "raw_text": "EGPC 181750Z 27021KT 9999 FEW032 14\/06 1003", "barometer": { "hg": null, "kpa": null, "mb": null }, "clouds": [ { "code": "FEW", "text": "Few", "base_feet_agl": 3200, "base_meters_agl": 975.36 } ], "dewpoint": { "celsius": 6, "fahrenheit": 43 }, "elevation": { "feet": 128, "meters": 39 }, "flight_category": "VFR", "humidity_percent": 59, "temperature": { "celsius": 14, "fahrenheit": 57 }, "visibility": { "miles": "Greater than 6", "meters": "10,000+" }, "wind": { "degrees": 270, "speed_kts": 21, "speed_mph": 24, "speed_mps": 11 } } ] }

**Comment by lilopkins** [comment]
In truth, the modified string without the 'Q' is not a METAR that should ever occur, however the aim of this library is to provide a safe interface whilst *attempting* to parse the library. Although checkwx may have also failed in parsing the data, I agree that this library should certainly not panic, and should instead return an error object.
I will work on fixing this now.

**Comment by ed-davies** [comment]
Thanks for the quick fix but another METAR from my database for a few days later (2018-06-21) also had a missing character which caused a panic. I'd suggest a more widespread review of the assumptions made during parsing so errors are picked up more systematically.

The second problem METAR is:

EGPC 211650Z 33026G37KT 9999 FEW021 12/7 Q1026

with a missing leading digit on the dew point (should be 12/07, presumably).
